name: Terraform Plan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-merge:
    name: branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2

    - name: Run prepare.sh
      run: |
        echo ${{ github.ref == 'refs/heads/main' ? 'production' : github.ref == 'refs/heads/staging' ? 'staging' : 'develop' }}
        chmod +x .prepare.sh
        #./.prepare.sh
