name: Terraform Plan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-merge:
    name: branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Run prepare.sh
      env:
        ENV_NAME: ${{ github.ref_name }}
      run: |
        chmod +x .prepare.sh
        ./.prepare.sh
